### ISSUE TITLE
Error running sample file

### ISSUE THREAD

**Issue by cagescudero** [BIONF/HaMStR#24] opened 2020-02-03 14:22 UTC
Hello

I installed HaMStR using conda. I ran the `setup_hamstr | tee log.txt` and it appears that there was no error during the setup.

I tried running the sample file but I get the following error.

```
There was an error running HaMStR v.13.2.10

VERSION:	HaMStR v.13.2.10

HOSTNAME	lmu-thesis1


USER DEFINED PARAMTERS (inc. default values)

	 -append:	not set
	 -blastpath:	/home/ubuntu/tools/HaMStR/blast_dir/
	 -checkCoorthologsRef:	not set
	 -cleartmp:	not set
	 -concat:	not set
	 -est:	not set
	 -eval_blast:	0.0001
	 -eval_hmmer:	0.0001
	 -filter:	F
	 -hit_limit:	not set
	 -hmm:	not set
	 -hmmpath:	/home/ubuntu/tools/HaMStR/core_orthologs/
	 -hmmset:	ppkdOcJ
	 -intron:	k
	 -longhead:	not set
	 -nonoverlapping_cos:	not set
	 -outpath:	/home/ubuntu/tools/HaMStR/output/ppkdOcJ
	 -protein:	1
	 -rbh:	not set
	 -refspec:	HUMAN@9606@1
	 -relaxed:	not set
	 -representative:	not set
	 -reuse:	not set
	 -sequence_file:	DROME@7227@1.fa
	 -show_hmmsets:	not set
	 -sort_global_align:	not set
	 -strict:	not set
	 -taxon:	DROME@7227@1
	 -ublast:	0
INFILE PROCESSING

	A modified infile DROME@7227@1.fa.mod already exists. Using this one
	Newlines from the infile have been removed

CHECKING FOR PROGRAMS

	check for blastp succeeded
	check for hmmsearch succeeded

CHECKING FOR HMMs

	running HaMStR with all hmms in /home/ubuntu/tools/HaMStR/core_orthologs//ppkdOcJ/hmm_dir
	check for /home/ubuntu/tools/HaMStR/core_orthologs//ppkdOcJ/ppkdOcJ.fa succeeded

CHECKING TAXON NAME

	using default taxon DROME@7227@1 for all sequences

CHECKING FOR REFERENCE TAXON

	 Reference species for the re-blast: HUMAN@9606@1

CHECKING FOR BLAST DATABASES

	check for /home/ubuntu/tools/HaMStR/blast_dir//HUMAN@9606@1/HUMAN@9606@1 succeeded

CHECKING FOR REFERENCE FASTA FILES

	Removing line breaks from /home/ubuntu/tools/HaMStR/genome_dir/HUMAN@9606@1/HUMAN@9606@1.fa.
FATAL: Problems running the script nentferner.pl

PROGRAM OPTIONS

	hmmsearch will run with an e-value limit of 0.0001
	re-blast hit_limit: none applied
	Blast will run with an evalue limit of 0.0001

	check for low complexity filter setting succeeded. Chosen value is F
	HaMStR was called without the -representative option. More than one ortholog may be identified per core-ortholog group!Evaluation of predicted HaMStR orthologs.
Error: Could not find /home/ubuntu/tools/HaMStR/data/ppkdOcJ.extended.fa
```

Do you know what could be causing this error ?

Thank you!

Regards,
Cata

**Comment by trvinh** [comment] 2020-02-03 16:01
@ebersber hi Ingo, do you have any idea how to troubleshoot this error?

**Comment by ebersber** [comment] 2020-02-03 16:22
Hi Cata,
Can you please provide with the command line call? Moreover, your installation does not find the script 'nentferner.pl' which is located in the PATHTOHAMSTR/HaMStR/bin directory.
There are two things to do for the start
First, Could you please tell me what is written in line 199 of the hamstr.pl script? It should read something like 
my $path =  '/share/project/ingo/Applications/HaMStR';
Second, can you confirm that the path, which is specified in line 199 is indeed the path where your HaMStR directory is located in? Or did you happen to rename something?

@trvinh Vinh, we should switch to relative rather than absolute paths...

**Comment by cagescudero** [comment] 2020-02-03 17:42
Hello,

This is how I called the program 
`perl oneSeq.pl -seqFile=infile.fa -seqid=P83876 -refspec=HUMAN@9606@1 -minDist=genus -maxDist=kingdom -coreOrth=5 -cleanup -global`

Script `nentferner.pl` is in the bin directory.

The line 199 of the `hamstr.pl` is `my $path =  '/home/ubuntu/tools/HaMStR';` which is the PATH where my HaMStR is installed.

Best,
Cata

**Comment by trvinh** [comment] 2020-02-03 17:46
@Cataescuderoo @ebersber 
I could reproduce the error using the same command. This is the error I got with `nentferner.pl`, it happened with both conda and non-conda version :-( 
```
Building up the taxonomy tree. Start 1580749720
Finished building the taxonomy tree: 1580749729
Building hash tree
Processing leafs...
Finished leafs
Processing ancestor nodes
Finished processing ancestor nodes
Finished building hash tree
Returning hash tree...
In round 0 running hmmbuild on /Users/bemun/Desktop/bionf/HaMStR/core_orthologs/GCdNohw/GCdNohw.aln
# hmmbuild :: profile HMM construction from multiple sequence alignments
# HMMER 3.2.1 (June 2018); http://hmmer.org/
# Copyright (C) 2018 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# input alignment file:             /Users/bemun/Desktop/bionf/HaMStR/core_orthologs/GCdNohw/GCdNohw.aln
# output HMM file:                  /Users/bemun/Desktop/bionf/HaMStR/core_orthologs/GCdNohw/hmm_dir/GCdNohw.hmm
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# idx name                  nseq  alen  mlen eff_nseq re/pos description
#---- -------------------- ----- ----- ----- -------- ------ -----------
1     GCdNohw                  1   142   142     0.36  0.591

# CPU time: 0.09u 0.00s 00:00:00.09 Elapsed: 00:00:00.09
Hamstr species: Pan troglodytes - PANTR@9598@1
hamstr for taxon: PANTR@9598@1
setting dboutpath to .
nentferner.pl succeeded.
checking for sequence type:
checking for the blast program:	succeeded
checking for hmmsearch:	succeeded
checking for genewise:		succeeded
checking for presence of the hmm files:		succeeded
checking for presence of the core-ortholog file:		succeeded
testing whether the taxon has been determined:	succeeded
checking for reference species and blast-dbs:	succeeded
checking for blast-dbs:	succeeded
checking for reference fasta files:
removing newlines from /Users/bemun/Desktop/bionf/HaMStR/genome_dir/HUMAN@9606@1/HUMAN@9606@1.fa such that a sequence forms a consecutive string

newlines will be removed without replacement
1000 lines processed
2000 lines processed
3000 lines processed
4000 lines processed
5000 lines processed
6000 lines processed
7000 lines processed
8000 lines processed
9000 lines processed
10000 lines processed
11000 lines processed
12000 lines processed
13000 lines processed
14000 lines processed
15000 lines processed
16000 lines processed
17000 lines processed
18000 lines processed
19000 lines processed
20000 lines processed
ln: /Users/bemun/Desktop/bionf/HaMStR/genome_dir/HUMAN@9606@1/HUMAN@9606@1.fa.mod: File exists
checking for low complexity filter setting:	succeeded


There was an error running HaMStR v.13.2.10

VERSION:	HaMStR v.13.2.10

HOSTNAME	Thanhs-MacBook-Air.local


USER DEFINED PARAMTERS (inc. default values)

	 -append:	not set
	 -blastpath:	/Users/bemun/Desktop/bionf/HaMStR/blast_dir/
	 -checkCoorthologsRef:	not set
	 -cleartmp:	not set
	 -concat:	not set
	 -est:	not set
	 -eval_blast:	1e-05
	 -eval_hmmer:	1e-05
	 -filter:	F
	 -hit_limit:	not set
	 -hmm:	not set
	 -hmmpath:	/Users/bemun/Desktop/bionf/HaMStR/core_orthologs/
	 -hmmset:	GCdNohw
	 -intron:	k
	 -longhead:	not set
	 -nonoverlapping_cos:	not set
	 -outpath:	/Users/bemun/Desktop/bionf/HaMStR/output/GCdNohw
	 -protein:	1
	 -rbh:	not set
	 -refspec:	HUMAN@9606@1
	 -relaxed:	not set
	 -representative:	not set
	 -reuse:	not set
	 -sequence_file:	PANTR@9598@1.fa
	 -show_hmmsets:	not set
	 -sort_global_align:	not set
	 -strict:	not set
	 -taxon:	PANTR@9598@1
	 -ublast:	0
INFILE PROCESSING

	A modified infile PANTR@9598@1.fa.mod already exists. Using this one
	Newlines from the infile have been removed

CHECKING FOR PROGRAMS

	check for blastp succeeded
	check for hmmsearch succeeded

CHECKING FOR HMMs

	running HaMStR with all hmms in /Users/bemun/Desktop/bionf/HaMStR/core_orthologs//GCdNohw/hmm_dir
	check for /Users/bemun/Desktop/bionf/HaMStR/core_orthologs//GCdNohw/GCdNohw.fa succeeded

CHECKING TAXON NAME

	using default taxon PANTR@9598@1 for all sequences

CHECKING FOR REFERENCE TAXON

	 Reference species for the re-blast: HUMAN@9606@1

CHECKING FOR BLAST DATABASES

	check for /Users/bemun/Desktop/bionf/HaMStR/blast_dir//HUMAN@9606@1/HUMAN@9606@1 succeeded

CHECKING FOR REFERENCE FASTA FILES

	Removing line breaks from /Users/bemun/Desktop/bionf/HaMStR/genome_dir/HUMAN@9606@1/HUMAN@9606@1.fa.
FATAL: Problems running the script nentferner.pl

PROGRAM OPTIONS

	hmmsearch will run with an e-value limit of 1e-05
	re-blast hit_limit: none applied
	Blast will run with an evalue limit of 1e-05

	check for low complexity filter setting succeeded. Chosen value is F
	HaMStR was called without the -representative option. More than one ortholog may be identified per core-ortholog group!No Candidate was found for PANTR@9598@1
```
I checked the files location, it seems to be all correct (`/Users/bemun/Desktop/bionf/HaMStR/bin/nentferner.pl`), and this perl script was also able to run (otherwise we will not get the output lines `??? lines processed`, won't we?). I didn't change anything on the `hamstr.pl` file since 2 months....

**Comment by cagescudero** [comment] 2020-02-03 17:57
I tried running the `nentferner.pl` separately since is the one that is giving the error, but it finished without the fatal error. Maybe is the step after this ?

This is the command I tried:
`../bin/nentferner.pl -in=HUMAN@9606@1.fa -out=HUMAN@9606@1.fa.tmp -replace `

**Comment by trvinh** [comment] 2020-02-03 18:11
@ebersber 
Hi Ingo, I tracked the error message and I think this one causes the issue (line 1186-1189 in `hamstr.pl`)

```
if (! -e "$referencedb.mod") {
     print "$referencedb.mod NOT FOUND - TEST\n"; # added by vinh
     push @log, "${bold}FATAL:${norm} Problems running the script nentferner.pl";
     $check = 0;
}
```

Some how the `$referencedb.mod` couldn't be found/read. In case of my example using the `infile.fa`, it would be `/Users/bemun/Desktop/bionf/HaMStR/genome_dir/HUMAN@9606@1/HUMAN@9606@1.fa.mod`. However, it conflicted with the previous line in the log file, which said that file exists:

```
...
16000 lines processed
17000 lines processed
18000 lines processed
19000 lines processed
20000 lines processed
ln: /Users/bemun/Desktop/bionf/HaMStR/genome_dir/HUMAN@9606@1/HUMAN@9606@1.fa.mod: File exists
/Users/bemun/Desktop/bionf/HaMStR/genome_dir/HUMAN@9606@1/HUMAN@9606@1.fa.mod NOT FOUND - TEST
checking for low complexity filter setting:	succeeded
```

**Comment by trvinh** [comment] 2020-02-03 18:13
@Cataescuderoo I think the `nentferner.pl` file works just fine. The error message was confusing. We will try to solve the problem and let you know soon :-)

**Comment by ebersber** [comment] 2020-02-03 22:41
@Cataescuderoo If Vinh can reproduce the error, then we will have it solved soon. I am a bit puzzled though, because for me all worked fine four days ago...

**Comment by ebersber** [comment] 2020-02-04 10:31
@Cataescuderoo @trvinh The solution is simple. We have some dead links in the genome_dir, which cause the trouble. Please do the following:
1. Enter the HaMStR directory
2. Enter the genome_dir: _cd genome_dir_
3. remove the dead links by typing: _rm */*.mod_ from within the genome_dir
4. move one up and into the _data_ directory: _cd ../data
5. run oneseq.pl on the test file: perl oneSeq.pl -seqFile=infile.fa -seqname=P83876 -refspec=HUMAN@9606@1 -minDist=genus -maxDist=kingdom -coreOrth=5 -cleanup -global

**Comment by trvinh** [comment] 2020-02-04 10:52
@ebersber thanks for figuring it out. I will remove all the *.mod* files from the *genome_dir* and make a new update very soon. 
@Cataescuderoo many thanks for contacting us about the problem! I will close this issue now :-)

**Closed as completed by trvinh** 2020-02-04 10:52 UTC
